### ISSUE TITLE
Error to execute JAR file

### ISSUE THREAD

**Issue by thiagolmoraes** [it-gorillaz/lnk2pwn#1]
Here is a summary of the issue when execute jar file.

**Error Details:**

```
Exception: java.lang.NoClassDefFoundError
Class: com.alee.managers.style.StyleManager
ExceptionInInitializerError with a NullPointerException in thread "main"
```

**Context:**

The project is using the weblaf library, and the issue seems to be related to the initialization of the StyleManager class within this library.

**Steps to Reproduce:**

Execute the application.

**Comment by tommelo** [comment]
> Here is a summary of the issue when execute jar file.
> 
> **Error Details:**
> 
> ```
> Exception: java.lang.NoClassDefFoundError
> Class: com.alee.managers.style.StyleManager
> ExceptionInInitializerError with a NullPointerException in thread "main"
> ```
> 
> **Context:**
> 
> The project is using the weblaf library, and the issue seems to be related to the initialization of the StyleManager class within this library.
> 
> **Steps to Reproduce:**
> 
> Execute the application. Observe the mentioned errors during the initialization process.

Hey @thiagolmoraes could you also share which Java version and OS you're running?
Also, just to confirm, you are trying to run the jar(release) file and not the project from the source, right?

Thanks.

**Comment by thiagolmoraes** [comment]
> d not the project from the source, right?
> 
> Thanks.

**Comment by thiagolmoraes** [comment]
> > Here is a summary of the issue when execute jar file.
> > **Error Details:**
> > ```
> > Exception: java.lang.NoClassDefFoundError
> > Class: com.alee.managers.style.StyleManager
> > ExceptionInInitializerError with a NullPointerException in thread "main"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Context:**
> > The project is using the weblaf library, and the issue seems to be related to the initialization of the StyleManager class within this library.
> > **Steps to Reproduce:**
> > Execute the application. Observe the mentioned errors during the initialization process.
> 
> Hey @thiagolmoraes could you also share which Java version and OS you're running? Also, just to confirm, you are trying to run the jar(release) file and not the project from the source, right?
> 
> Thanks.

Hey Tom,

I trying to run from release, 

```
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Debian-2)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-2, mixed mode, sharing)
```


Also I was trying to compile from source using apache maven 3.6.3 , but the error above was provided by running release (JAR FILE)

**Comment by tommelo** [comment]
> > > Here is a summary of the issue when execute jar file.
> > > **Error Details:**
> > > ```
> > > Exception: java.lang.NoClassDefFoundError
> > > Class: com.alee.managers.style.StyleManager
> > > ExceptionInInitializerError with a NullPointerException in thread "main"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Context:**
> > > The project is using the weblaf library, and the issue seems to be related to the initialization of the StyleManager class within this library.
> > > **Steps to Reproduce:**
> > > Execute the application. Observe the mentioned errors during the initialization process.
> > 
> > 
> > Hey @thiagolmoraes could you also share which Java version and OS you're running? Also, just to confirm, you are trying to run the jar(release) file and not the project from the source, right?
> > Thanks.
> 
> Hey Tom,
> 
> I trying to run from release,
> 
> ```
> openjdk 17.0.9 2023-10-17
> OpenJDK Runtime Environment (build 17.0.9+9-Debian-2)
> OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-2, mixed mode, sharing)
> ```
> 
> Also I was trying to compile from source using apache maven 3.6.3 , but the error above was provided by running release (JAR FILE)

Yes, the `weblaf` version that this project uses is not supported in newer Java versions.
The last version I was able to get running is:
```
openjdk version "1.8.0_332"
OpenJDK Runtime Environment Corretto-8.332.08.1 (build 1.8.0_332-b08)
OpenJDK 64-Bit Server VM Corretto-8.332.08.1 (build 25.332-b08, mixed mode)
```
I can see weblaf has some opened issues related to that: https://github.com/mgarin/weblaf/issues/667

I could also make a cli version of this project(that does not require any UI) but I am not sure if it's worth it.
Not sure if this bypass still works on newer Windows versions.

**Comment by thiagolmoraes** [comment]
> > > > Here is a summary of the issue when execute jar file.
> > > > **Error Details:**
> > > > ```
> > > > Exception: java.lang.NoClassDefFoundError
> > > > Class: com.alee.managers.style.StyleManager
> > > > ExceptionInInitializerError with a NullPointerException in thread "main"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > **Context:**
> > > > The project is using the weblaf library, and the issue seems to be related to the initialization of the StyleManager class within this library.
> > > > **Steps to Reproduce:**
> > > > Execute the application. Observe the mentioned errors during the initialization process.
> > > 
> > > 
> > > Hey @thiagolmoraes could you also share which Java version and OS you're running? Also, just to confirm, you are trying to run the jar(release) file and not the project from the source, right?
> > > Thanks.
> > 
> > 
> > Hey Tom,
> > I trying to run from release,
> > ```
> > openjdk 17.0.9 2023-10-17
> > OpenJDK Runtime Environment (build 17.0.9+9-Debian-2)
> > OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-2, mixed mode, sharing)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also I was trying to compile from source using apache maven 3.6.3 , but the error above was provided by running release (JAR FILE)
> 
> Yes, the `weblaf` version that this project uses is not supported in newer Java versions. The last version I was able to get running is:
> 
> ```
> openjdk version "1.8.0_332"
> OpenJDK Runtime Environment Corretto-8.332.08.1 (build 1.8.0_332-b08)
> OpenJDK 64-Bit Server VM Corretto-8.332.08.1 (build 25.332-b08, mixed mode)
> ```
> 
> I can see weblaf has some opened issues related to that: [mgarin/weblaf#667](https://github.com/mgarin/weblaf/issues/667)
> 
> I could also make a cli version of this project(that does not require any UI) but I am not sure if it's worth it. Not sure if this bypass still works on newer Windows versions.

I found this version and different, there is another version, it starts running but an error pops up

```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) Server VM (build 25.391-b13, mixed mode)
```


```
java -jar lnk2pwn-1.0.0.jar 
2023-12-01 14:36:01.595  INFO 19709 --- [           main] c.i.l.Lnk2Pwn                            : Starting Lnk2Pwn v1.0.0 on kali with PID 19709 (/home/kali/Downloads/lnk2pwn-1.0.0.jar started by kali in /home/kali/Downloads)
2023-12-01 14:36:01.601  INFO 19709 --- [           main] c.i.l.Lnk2Pwn                            : No active profile set, falling back to default profiles: default
2023-12-01 14:36:02.377  WARN 19709 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'showAboutDialogAction': Unsatisfied dependency expressed through field 'aboutDialog'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aboutDialog' defined in URL [jar:file:/home/kali/Downloads/lnk2pwn-1.0.0.jar!/BOOT-INF/classes!/com/itgorillaz/lnk2pwn/view/AboutDialog.class]: Instantiation of bean failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk1.8.0_391/jre/lib/i386/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
2023-12-01 14:36:02.386  INFO 19709 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-12-01 14:36:02.388 ERROR 19709 --- [           main] o.s.b.SpringApplication                  : Application run failed Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'showAboutDialogAction': Unsatisfied dependency expressed through field 'aboutDialog'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aboutDialog' defined in URL [jar:file:/home/kali/Downloads/lnk2pwn-1.0.0.jar!/BOOT-INF/classes!/com/itgorillaz/lnk2pwn/view/AboutDialog.class]: Instantiation of bean failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk1.8.0_391/jre/lib/i386/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory

```

**Comment by tommelo** [comment]
ok, I will start upgrading the project to work with newer java versions.

@thiagolmoraes meanwhile, did you try to install the libxtst?
```
ava.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk1.8.0_391/jre/lib/i386/libawt_xawt.so
```
https://askubuntu.com/questions/674579/libawt-xawt-so-libxext-so-6-cannot-open-shared-object-file-no-such-file-or-di

**Comment by thiagolmoraes** [comment]
> ok, I will start upgrading the project to work with newer java versions.
> 
> @thiagolmoraes meanwhile, did you try to install the libxtst?
> 
> ```
> ava.lang.UnsatisfiedLinkError: /usr/lib/jvm/jdk1.8.0_391/jre/lib/i386/libawt_xawt.so
> ```
> 
> https://askubuntu.com/questions/674579/libawt-xawt-so-libxext-so-6-cannot-open-shared-object-file-no-such-file-or-di

That is worked! Thanks very much! :D
